// Generated by scripts/export-schema.py from privacytrace.models. DO NOT EDIT.
// JSON shapes only; semantic constraints are enforced by the Python API.

export type AnalysisJob = {
  "id": string;
  "sample_id": string;
  "input_mode": "SYNTHETIC" | "APK";
  "state": "QUEUED" | "INTAKE" | "STATIC_ANALYSIS" | "POLICY_PARSING" | "EVALUATING" | "REPORTING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
  "ruleset_version": string;
  "created_at": string;
  "package_name"?: string | null;
  "version_code"?: number | null;
  "region"?: string | null;
  "product_scope"?: string | null;
  "error"?: string | null;
};

export type ApiCall = {
  "target_descriptor": string;
  "rule_id": string;
  "ruleset_version": string;
  "context"?: Record<string, string>;
};

export type ContextualHint = {
  "value": string;
  "basis"?: "CONTEXTUAL_PURPOSE_HINT";
  "evidence_ids": Array<string>;
};

export type EvaluationInput = {
  "job": AnalysisJob;
  "evidence": Array<Evidence>;
  "behaviors": Array<PrivacyBehavior>;
  "policy_documents": Array<PolicyDocument>;
  "policy_claims": Array<PolicyClaim>;
};

export type EvaluationResult = {
  "job_id": string;
  "ruleset_version": string;
  "issues": Array<PrivacyIssue>;
};

export type Evidence = {
  "id": string;
  "kind": "MANIFEST" | "API" | "SDK" | "POLICY_DOCUMENT" | "POLICY_SENTENCE";
  "status": "STATIC_POTENTIAL" | "DECLARED";
  "source": string;
  "locator": string;
  "excerpt"?: string;
  "document_id"?: string | null;
  "artifact_sha256"?: string | null;
  "start_offset"?: number | null;
  "end_offset"?: number | null;
  "api_call"?: ApiCall | null;
};

export type MatchStatus = "EXACT_MATCH" | "CATEGORY_MATCH" | "NOT_DECLARED" | "POLICY_SOURCE_CONFLICT" | "AMBIGUOUS_DISCLOSURE" | "INSUFFICIENT_EVIDENCE";

export type PolicyApplicability = {
  "package_name"?: string | null;
  "version_codes"?: Array<number>;
  "regions"?: Array<string>;
  "product_scope"?: string | null;
};

export type PolicyArtifact = {
  "text": string;
  "sha256": string;
  "normalization"?: "NONE";
};

export type PolicyClaim = {
  "id": string;
  "document_id": string;
  "data_type": string;
  "action"?: "ACCESS" | "UNKNOWN";
  "polarity"?: "AFFIRMATIVE" | "NEGATIVE" | "UNKNOWN";
  "condition"?: string | null;
  "subject"?: "HOST_APP" | "THIRD_PARTY" | "UNKNOWN";
  "declared_purpose"?: string | null;
  "declared_recipient"?: string | null;
  "basis"?: "POLICY_DECLARATION";
  "ambiguity_flags"?: Array<"CATCH_ALL" | "UNCLEAR_ACTION">;
  "evidence_ids": Array<string>;
};

export type PolicyDocument = {
  "id": string;
  "source_type": PolicySource;
  "title": string;
  "version": string;
  "captured_at": string;
  "artifact": PolicyArtifact;
  "completeness": "COMPLETE" | "PARTIAL";
  "extraction_status"?: "NOT_STARTED" | "SUCCEEDED" | "PARTIAL" | "FAILED";
  "review_status"?: "UNREVIEWED" | "REVIEWED";
  "attachments_status"?: "NOT_CHECKED" | "COMPLETE" | "MISSING";
  "applicability"?: PolicyApplicability;
  "evidence_id": string;
};

export type PolicySource = "IN_APP_POLICY" | "STORE_POLICY" | "OFFICIAL_WEB_POLICY" | "SDK_POLICY";

export type PrivacyBehavior = {
  "id": string;
  "data_type": string;
  "action"?: "ACCESS" | "CAPABILITY";
  "purpose"?: "UNKNOWN";
  "recipient"?: "UNKNOWN";
  "transfer"?: "UNKNOWN";
  "temporal_scope"?: "UNKNOWN";
  "evidence_ids": Array<string>;
  "contextual_hints"?: Array<ContextualHint>;
};

export type PrivacyIssue = {
  "id": string;
  "behavior_id": string;
  "data_type": string;
  "status": MatchStatus;
  "evidence_status"?: "STATIC_POTENTIAL";
  "policy_document_ids": Array<string>;
  "evidence_ids": Array<string>;
  "explanation": string;
  "scope"?: "DATA_TYPE_DISCLOSURE";
  "requires_review"?: boolean;
};
